// One-off: resolves curated YouTube video ids -> {id, title, channel, ...}
// via YouTube's public oEmbed endpoint (no API key), and writes
// src/data/youtubeClips.ts. oEmbed success doubles as an embeddability check:
// private / removed / embedding-disabled videos fail and are dropped.
// Run: node scripts/gen-youtube.mjs
import { writeFileSync } from 'node:fs'

// kind: 'official' = studio/distributor PVs & clips (stable, embeddable)
//       'amv'      = fan edits / compilations (oEmbed gate filters non-embeddable)
const CURATED = [
  // --- Official anime PVs / trailers (ids sourced from AniList) ---
  ['LHtdKWJdif4', 'official'], // Attack on Titan
  ['6vMuWuWlW4I', 'official'], // Demon Slayer
  ['pkKu9hLT-t8', 'official'], // Jujutsu Kaisen
  ['AhqVltWDqFA', 'official'], // My Hero Academia
  ['d6kBeJjTGnY', 'official'], // Hunter x Hunter
  ['RzmFKUDOUgw', 'official'], // One Punch Man
  ['C8Jl_-b7ju0', 'official'], // Sword Art Online
  ['k4xGqY5IDBE', 'official'], // Your Name
  ['Sy4bPCuzfiQ', 'official'], // A Silent Voice
  ['mV39saBlBLI', 'official'], // Mob Psycho 100
  ['v4yLeNt-kCU', 'official'], // Chainsaw Man
  ['ofXigq9aIpo', 'official'], // Spy x Family
  ['IwpJJiQkZzI', 'official'], // Kaguya-sama
  ['7YZzYeBartM', 'official'], // Dr. Stone
  ['_grmduuECm4', 'official'], // Violet Evergarden
  ['9kLRkH9zC5k', 'official'], // Haikyu!!
  ['o0TZj_d3Yfg', 'official'], // Bunny Girl Senpai
  ['27OZc-ku6is', 'official'], // Steins;Gate
  ['vFfXjuVA1Jk', 'official'], // Re:Zero
  ['ya570uUgQNc', 'official'], // Toradora!
  // --- AMV / fan-edit candidates (filtered by the oEmbed gate) ---
  ['WhCGieof6do', 'amv'],
  ['XgChE1Efa4c', 'amv'],
  ['Vcyk7qIX-hc', 'amv'],
  ['ibDZu-AagBE', 'amv'],
  ['CMF3qeu7fHY', 'amv'],
]

const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

async function oembed(id) {
  const url = `https://www.youtube.com/oembed?url=${encodeURIComponent(
    `https://www.youtube.com/watch?v=${id}`,
  )}&format=json`
  const res = await fetch(url, { headers: { 'User-Agent': 'Mozilla/5.0' } })
  if (!res.ok) throw new Error(`oembed ${id} -> ${res.status}`)
  return res.json()
}

async function oembedRetry(id, tries = 3) {
  for (let i = 0; i < tries; i++) {
    try {
      return await oembed(id)
    } catch (e) {
      if (i === tries - 1) throw e
      await sleep(500)
    }
  }
}

const out = []
for (const [id, kind] of CURATED) {
  await sleep(150)
  try {
    const o = await oembedRetry(id)
    out.push({
      id,
      kind,
      title: o.title ?? 'Anime clip',
      channel: o.author_name ?? 'YouTube',
      channelUrl: o.author_url ?? `https://www.youtube.com/watch?v=${id}`,
      thumbnail: o.thumbnail_url ?? null,
    })
    console.log(`ok   ${kind.padEnd(8)} ${id}  ${o.author_name} — ${o.title}`)
  } catch (e) {
    console.log(`skip ${kind.padEnd(8)} ${id}  (${e.message})`)
  }
}

const body = `// AUTO-GENERATED by scripts/gen-youtube.mjs — curated YouTube anime clips.
// Each video is embeddable (validated via YouTube oEmbed) and credited to its channel.
export interface YouTubeClip {
  id: string
  kind: 'official' | 'amv'
  title: string
  channel: string
  channelUrl: string
  thumbnail: string | null
}

export const YOUTUBE_CLIPS: YouTubeClip[] = ${JSON.stringify(out, null, 2)}
`

writeFileSync(new URL('../src/data/youtubeClips.ts', import.meta.url), body)
console.log(`\nWrote ${out.length} clips to src/data/youtubeClips.ts`)
