// AUTO-GENERATED by scripts/gen-youtube.mjs — curated YouTube anime clips.
// Each video is embeddable (validated via YouTube oEmbed) and credited to its channel.
export interface YouTubeClip {
  id: string
  kind: 'official' | 'amv'
  title: string
  channel: string
  channelUrl: string
  thumbnail: string | null
}

export const YOUTUBE_CLIPS: YouTubeClip[] = [
  {
    "id": "LHtdKWJdif4",
    "kind": "official",
    "title": "TVアニメ「進撃の巨人」PV 第２弾",
    "channel": "ぽにきゃん-Anime PONY CANYON",
    "channelUrl": "https://www.youtube.com/@PONYCANYON_anime",
    "thumbnail": "https://i.ytimg.com/vi/LHtdKWJdif4/hqdefault.jpg"
  },
  {
    "id": "6vMuWuWlW4I",
    "kind": "official",
    "title": "Demon Slayer: Kimetsu no Yaiba Trailer 2",
    "channel": "Aniplex USA",
    "channelUrl": "https://www.youtube.com/@AniplexUSA",
    "thumbnail": "https://i.ytimg.com/vi/6vMuWuWlW4I/hqdefault.jpg"
  },
  {
    "id": "pkKu9hLT-t8",
    "kind": "official",
    "title": "JUJUTSU KAISEN | OFFICIAL TRAILER",
    "channel": "Crunchyroll",
    "channelUrl": "https://www.youtube.com/@crunchyroll",
    "thumbnail": "https://i.ytimg.com/vi/pkKu9hLT-t8/hqdefault.jpg"
  },
  {
    "id": "AhqVltWDqFA",
    "kind": "official",
    "title": "アニメ『僕のヒーローアカデミア』PV第4弾",
    "channel": "TOHO animation チャンネル",
    "channelUrl": "https://www.youtube.com/@TOHOanimation",
    "thumbnail": "https://i.ytimg.com/vi/AhqVltWDqFA/hqdefault.jpg"
  },
  {
    "id": "d6kBeJjTGnY",
    "kind": "official",
    "title": "Hunter X Hunter Set 1- Official Extended Trailer",
    "channel": "vizmedia",
    "channelUrl": "https://www.youtube.com/@vizmedia",
    "thumbnail": "https://i.ytimg.com/vi/d6kBeJjTGnY/hqdefault.jpg"
  },
  {
    "id": "RzmFKUDOUgw",
    "kind": "official",
    "title": "TVアニメ『ワンパンマン』PV第3弾",
    "channel": "バンダイナムコフィルムワークス チャンネル",
    "channelUrl": "https://www.youtube.com/@bandainamcofilmworks",
    "thumbnail": "https://i.ytimg.com/vi/RzmFKUDOUgw/hqdefault.jpg"
  },
  {
    "id": "C8Jl_-b7ju0",
    "kind": "official",
    "title": "Sword Art Online English Dub Trailer",
    "channel": "Aniplex USA",
    "channelUrl": "https://www.youtube.com/@AniplexUSA",
    "thumbnail": "https://i.ytimg.com/vi/C8Jl_-b7ju0/hqdefault.jpg"
  },
  {
    "id": "k4xGqY5IDBE",
    "kind": "official",
    "title": "「君の名は。」予告",
    "channel": "東宝MOVIEチャンネル",
    "channelUrl": "https://www.youtube.com/@OfficialTohoMovie",
    "thumbnail": "https://i.ytimg.com/vi/k4xGqY5IDBE/hqdefault.jpg"
  },
  {
    "id": "Sy4bPCuzfiQ",
    "kind": "official",
    "title": "A Silent Voice - The Movie - Official Trailer (HD)",
    "channel": "Shout! Studios",
    "channelUrl": "https://www.youtube.com/@ShoutStudios",
    "thumbnail": "https://i.ytimg.com/vi/Sy4bPCuzfiQ/hqdefault.jpg"
  },
  {
    "id": "mV39saBlBLI",
    "kind": "official",
    "title": "TVアニメ『モブサイコ１００』 PV 第3弾",
    "channel": "Warner Bros. Japan Anime",
    "channelUrl": "https://www.youtube.com/@wbj_anime",
    "thumbnail": "https://i.ytimg.com/vi/mV39saBlBLI/hqdefault.jpg"
  },
  {
    "id": "v4yLeNt-kCU",
    "kind": "official",
    "title": "Chainsaw Man - Main Trailer ／『チェンソーマン』本予告",
    "channel": "MAPPA CHANNEL",
    "channelUrl": "https://www.youtube.com/@MAPPACHANNEL",
    "thumbnail": "https://i.ytimg.com/vi/v4yLeNt-kCU/hqdefault.jpg"
  },
  {
    "id": "ofXigq9aIpo",
    "kind": "official",
    "title": "SPY x FAMILY | MAIN TRAILER",
    "channel": "Crunchyroll",
    "channelUrl": "https://www.youtube.com/@crunchyroll",
    "thumbnail": "https://i.ytimg.com/vi/ofXigq9aIpo/hqdefault.jpg"
  },
  {
    "id": "IwpJJiQkZzI",
    "kind": "official",
    "title": "Kaguya-sama: Love Is War Trailer 2",
    "channel": "Aniplex USA",
    "channelUrl": "https://www.youtube.com/@AniplexUSA",
    "thumbnail": "https://i.ytimg.com/vi/IwpJJiQkZzI/hqdefault.jpg"
  },
  {
    "id": "7YZzYeBartM",
    "kind": "official",
    "title": "Dr. STONE | OFFICIAL PREVIEW",
    "channel": "Crunchyroll",
    "channelUrl": "https://www.youtube.com/@crunchyroll",
    "thumbnail": "https://i.ytimg.com/vi/7YZzYeBartM/hqdefault.jpg"
  },
  {
    "id": "_grmduuECm4",
    "kind": "official",
    "title": "Violet Evergarden | Now Streaming | Netflix",
    "channel": "Netflix Anime",
    "channelUrl": "https://www.youtube.com/@netflixanime",
    "thumbnail": "https://i.ytimg.com/vi/_grmduuECm4/hqdefault.jpg"
  },
  {
    "id": "9kLRkH9zC5k",
    "kind": "official",
    "title": "『ハイキュー!!』少年ジャンプ公式ＰＶ",
    "channel": "shonenjump_official",
    "channelUrl": "https://www.youtube.com/@shonenjumpofficial",
    "thumbnail": "https://i.ytimg.com/vi/9kLRkH9zC5k/hqdefault.jpg"
  },
  {
    "id": "o0TZj_d3Yfg",
    "kind": "official",
    "title": "Rascal Does Not Dream of Bunny Girl Senpai Trailer",
    "channel": "Aniplex USA",
    "channelUrl": "https://www.youtube.com/@AniplexUSA",
    "thumbnail": "https://i.ytimg.com/vi/o0TZj_d3Yfg/hqdefault.jpg"
  },
  {
    "id": "27OZc-ku6is",
    "kind": "official",
    "title": "シュタインズ・ゲート放送直前PV",
    "channel": "SGTVanime",
    "channelUrl": "https://www.youtube.com/@SGTVanime",
    "thumbnail": "https://i.ytimg.com/vi/27OZc-ku6is/hqdefault.jpg"
  },
  {
    "id": "vFfXjuVA1Jk",
    "kind": "official",
    "title": "【TVアニメ化決定】「Re:ゼロから始める異世界生活」特報PV",
    "channel": "mediafactory",
    "channelUrl": "https://www.youtube.com/@mediafactory",
    "thumbnail": "https://i.ytimg.com/vi/vFfXjuVA1Jk/hqdefault.jpg"
  },
  {
    "id": "ya570uUgQNc",
    "kind": "official",
    "title": "Toradora! - Official English Trailer",
    "channel": "NIS America",
    "channelUrl": "https://www.youtube.com/@NISAmerica",
    "thumbnail": "https://i.ytimg.com/vi/ya570uUgQNc/hqdefault.jpg"
  },
  {
    "id": "WhCGieof6do",
    "kind": "amv",
    "title": "Watching The GREATEST Anime AMV's of All Time!",
    "channel": "Nicholas Light TV",
    "channelUrl": "https://www.youtube.com/@NicholasLightTV",
    "thumbnail": "https://i.ytimg.com/vi/WhCGieof6do/hqdefault.jpg"
  },
  {
    "id": "XgChE1Efa4c",
    "kind": "amv",
    "title": "The Best [ AMV - Mix ] Anime Mix",
    "channel": "monomogu",
    "channelUrl": "https://www.youtube.com/@monomogu",
    "thumbnail": "https://i.ytimg.com/vi/XgChE1Efa4c/hqdefault.jpg"
  },
  {
    "id": "Vcyk7qIX-hc",
    "kind": "amv",
    "title": "Best of Anime - AMV Compilation HD",
    "channel": "RowdyOnliner",
    "channelUrl": "https://www.youtube.com/@rowdyonliner5524",
    "thumbnail": "https://i.ytimg.com/vi/Vcyk7qIX-hc/hqdefault.jpg"
  },
  {
    "id": "ibDZu-AagBE",
    "kind": "amv",
    "title": "Top 5 Best AMVs OF ALL TIME",
    "channel": "Mathwiz97X",
    "channelUrl": "https://www.youtube.com/@Mathwiz97X",
    "thumbnail": "https://i.ytimg.com/vi/ibDZu-AagBE/hqdefault.jpg"
  },
  {
    "id": "CMF3qeu7fHY",
    "kind": "amv",
    "title": "Middle of the Night「AMV」Anime Mix",
    "channel": "TumpyGFX",
    "channelUrl": "https://www.youtube.com/@TumpyGFX",
    "thumbnail": "https://i.ytimg.com/vi/CMF3qeu7fHY/hqdefault.jpg"
  }
]
